# Generated by Django 3.0.4 on 2020-04-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='createdAt',
        ),
    ]
