export const ABOUT_INFO_COLLAPSE = 'ABOUT_INFO_COLLAPSE'
export const ABOUT_CONTACTS_COLLAPSE = 'ABOUT_CONTACTS_COLLAPSE'
export const NAVBAR_COLLAPSE = 'NAVBAR_COLLAPSE'
export const CHANGE_THEME = 'CHANGE_THEME'